# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hexo
image: node:6.4.1

stages:
  - pages
  - deploy

pages:
  stage: pages
  tags:
    - hexo-public
  script:
    - cnpm install
    - ./node_modules/hexo/bin/hexo generate
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master

deploy:
  stage: deploy
  tags:
    - hexo-public
  script:
    - ./node_modules/hexo/bin/hexo deploy
  only:
    - master
