stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - hexo-public
  script:
    - cnpm install
    - hexo generate
  artifacts:
    paths:
      - public/
      - .deploy_git/

test:
  stage: test
  tags:
    - hexo-public
  script:
    - cnpm --version
  artifacts:
    paths:
      - public/
      - .deploy_git/

deploy:
  stage: deploy
  tags:
    - hexo-public
  script:
    - hexo deploy
