stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - hexo-public
  script:
    - cnpm install
    - hexo generate

test:
  stage: test
  tags:
    - hexo-public
  script:
    - hexo --version

deploy:
  stage: deploy
  tags:
    - hexo-public
  script:
    - hexo deploy
