stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - hexo-public
  script:
    - cnpm install
    - hexo generate
  artifacts:
    paths:
      - public/

deploy:
  stage: deploy
  tags:
    - hexo-public
  script:
    - hexo deploy
